app/urls.py
from django.urls import path
from . import views

app_name = "app"

urlpatterns = [
    path('', views.home, name='home'),
    path('start/chat/', views.startRoom, name='startRoom'),
    path('chat/<str:room_id>', views.enterRoom, name='enterRoom'),
    path('manage/online/', views.manageOnlineUsers, name="manageOnlineUsers"),
    path('location/update/', views.locationSharing, name="locationSharing"),
    path('lobby/<str:room_id>', views.waitRoom, name="waitRoom"),
    path('chat/response/', views.roomResponse, name='roomResponse',),
    path("sendInvite/", views.sendInvite, name="sendInvite"),
    path('delete/room/<str:room_id>', views.deleteRoom, name="deleteRoom"),
    path("chatroom", views.chatroom, name="chatroom")
]

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('logout/', views.user_logout, name="logout"),
    path('register/', views.registerView, name='registerView'),
    path('api/register/', views.register, name='register'),
    path('login/', views.loginView, name="loginView"),
    path("api/login/", views.user_login, name="login"),
    path('profile/<str:id>/', views.profile, name="profile"),
    path('search/', views.autocomplete, name='autocomplete'),
    path('follow/', views.follow_user, name='followUser'),
    path('profileapi/<str:id>/', views.profileAPI, name="profileAPI")
]

videochat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('auth/', include('user.urls')),
]

user/models.py
from django.db import models

# Create your models here.
from django.contrib.auth import get_user_model
User = get_user_model()

import uuid


class Profile(models.Model):
    user = models.OneToOneField(User, related_name="user_profile", on_delete=models.CASCADE)
    last_login = models.DateTimeField(blank=True, null=True)
    unique_id = models.CharField(max_length=8, default=str(uuid.uuid4())[:8])
    email_confirm = models.BooleanField(default=False, blank=True, null=True)
    mobile = models.CharField(max_length=10, blank=True, null=True)
    bio = models.CharField(max_length=50, blank=True, null=True)
    address = models.CharField(max_length=50, blank=True, null=True)
    follow = models.ManyToManyField(User, related_name="user_follow", blank=True, null=True)
    active = models.BooleanField(default=False)
    def __str__(self):
        return self.user.first_name if self.user.first_name else self.user.username

user/views.py
from django.shortcuts import render,redirect
from app.utils import Response
from django.contrib.auth import login,logout
from django.contrib.auth import get_user_model
User = get_user_model()

from .models import Profile
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate
from datetime import datetime
from django.db.models import Count, Q
from django.http import JsonResponse
# Create your views here.
import uuid
import json

@login_required
def user_logout(request):
    logout(request)
    return redirect('app:home')

def registerView(request):
    return render(request, "user/register.html")

def register(request):
    if request.method == "POST":
        email = request.POST.get("email")
        password1 = request.POST.get("password1")
        password2 = request.POST.get("password2")
        user_count = User.objects.filter(email=email).count()
        if user_count == 0:
            if password1 == password2:
                user = User(username=email, email=email)
                print(email,password1)
                user.set_password(password1)
                user.save()
                profile = Profile(user=user, unique_id=str(uuid.uuid4())[:8])
                profile.save()
                login(request,user)
                print(email + " registered")
                return Response("success", "registered successfully", status=200)
            else:
                return Response("failed", "password do not matched", status=400)
        else:
            return Response("failed", "User already exist", status=400)

def loginView(request):
    return render(request, "user/login.html")

def user_login(request):
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")
        user=authenticate(username=email,password=password)
        print(user)
        if user:
            user_profile = user.user_profile
            user_profile.last_login = datetime.now()
            user_profile.save()
            login(request, user)
            print(user.username + " logged in")
            return Response("success", "successfully logged in", status=200)
        else:
            print("Wrong credentials")
            return Response("failed", "login failed", status=400)

def profile(request, id):
    try:
        profile = Profile.objects.get(unique_id=id)
    except Exception as err:
        print(str(err))
        return render(request, "app/home.html")
    print(profile)
    return render(request, "user/profile.html", context={"profile": profile})


def profileAPI(request, id):
    if request.method == "POST":
        data = json.loads(request.body)
        name = data.get("user_name")
        email = data.get("user_email")
        
        mobile = data.get("user_mobile")
        address = data.get("user_address")
        bio = data.get("user_bio")
        print(name, email, mobile, address, bio)
        user = request.user
        profile = user.user_profile
        if user.username!=email and User.objects.filter(username=email).count() > 0:
            return redirect("user:profile", id=profile.unique_id)
        
        profile = Profile.objects.get(unique_id=id)
        profile.mobile = mobile
        profile.bio = bio
        profile.address = address
        profile.save()

        user.first_name = name
        user.email = email
        user.username = email
        user.save()

        return Response("success", "Profile updated", status=200)


@login_required
def autocomplete(request):
    if request.is_ajax():
        query = request.GET.get("term", "")
        profiles = User.objects.filter(Q(username__icontains=query) | Q(first_name__icontains=query))
        results = []
        # ext = ChatGroup.objects.annotate(c=Count('members')).filter(c=2,members__in=[request.user])
        for profile in profiles:
            results.append({
                "label":profile.first_name if profile.first_name else profile.username,
                "value":profile.user_profile.unique_id
                })
        if results==[]:
            results.append({"label":"No Match Found","value":""})
        return JsonResponse(results,safe=False)

    # elif request.method=="GET":
    #     code = request.GET.get("mysearchid")
    #     group = ChatGroup.objects.get(code = code)
    #     return redirect("chat:room" ,room_code=code)


@login_required
def follow_user(request):
    print(request.GET)
    try:
        id = request.GET.get("id")
        action = request.GET.get("action")
        user = User.objects.get(user_profile__unique_id=id)
        print(user, id, action)
        profile = request.user.user_profile
        if action == "follow":
            print("hello")
            profile.follow.add(user)
            profile.save()
            return JsonResponse({"result":True})
        elif action == "unfollow":
            profile.follow.remove(user)
            profile.save()
            return JsonResponse({"result":True})
        else:
            return JsonResponse({"result":False})
    except Exception as err:
        print(str(err))
        return JsonResponse({"result":False})

user/templates/user/login.html
{% extends "app/base.html" %}
{% block content %}
<style>
    body {
  background: #007bff;
  background: linear-gradient(to right, #0062E6, #33AEFF);
}

.btn-login {
  font-size: 0.9rem;
  letter-spacing: 0.05rem;
  padding: 0.75rem 1rem;
}

.btn-google {
  color: white !important;
  background-color: #ea4335;
}

.btn-facebook {
  color: white !important;
  background-color: #3b5998;
}

</style>
<br><br><br><br>
<body>
    <div class="container">
      <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
          <div class="card border-0 shadow rounded-3 my-5">
            <div class="card-body p-4 p-sm-5">
              <h5 class="card-title text-center mb-5 fw-light fs-5">Sign In</h5>
              <form>
                <div class="form-floating mb-3">
                  <input type="email" id="email" class="form-control" id="floatingInput" placeholder="name@example.com">
                  <label for="email">Email address</label>
                </div>
                <div class="form-floating mb-3">
                  <input type="password" id="password" class="form-control" id="floatingPassword" placeholder="Password">
                  <label for="password">Password</label>
                </div>
  
                <!-- <div class="form-check mb-3">
                  <input class="form-check-input" type="checkbox" value="" id="rememberPasswordCheck">
                  <label class="form-check-label" for="rememberPasswordCheck">
                    Remember password
                  </label>
                </div> -->
                <div class="d-grid">
                  <button class="btn btn-primary btn-login text-uppercase fw-bold" type="button" onclick="login();">Sign
                    in</button>
                </div>
                <!-- <hr class="my-4">
                <div class="d-grid mb-2">
                  <button class="btn btn-google btn-login text-uppercase fw-bold" type="submit">
                    <i class="fab fa-google me-2"></i> Sign in with Google
                  </button>
                </div>
                <div class="d-grid">
                  <button class="btn btn-facebook btn-login text-uppercase fw-bold" type="submit">
                    <i class="fab fa-facebook-f me-2"></i> Sign in with Facebook
                  </button>
                </div> -->
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
  

<script>
    const csrf = '{{csrf_token}}';
        function login(){
            email = document.getElementById("email").value;
            pass = document.getElementById("password").value;
            const formData = new FormData();
            formData.append('email', email);
            formData.append('password', pass);
            const otherPram={
                body:formData,
                method:"POST",
                headers: {
                    "X-CSRFToken": csrf
                },
                mode: "same-origin",
            };
            fetch("{% url 'user:login' %}", otherPram).then(res=>res.json())
            .then(data=>{
                console.log(data);
                if (data.status == "success"){
                  window.location = "{% url 'app:home' %}";
                }
                else{
                  alert(data.message)
                }
            });
        }

          document.addEventListener("keyup", function(event) {
              if (event.keyCode === 13) {
                  event.preventDefault();
                  login();
              }
          });
</script>

{% endblock content %}

user/templates/user/profile.html
{% extends "app/base.html" %}
{% block content %}

<style>
    .main-div{
        position: absolute;
        left:   15%;
        
    }

    body{
        background-color: #2e2d2b;
    }

    .sub-divs{
        border-radius: 10px;
        box-shadow: 0 8px 25px 0 rgba(74, 174, 217, 0.4), 0 6px 40px 0 rgba(74, 174, 217, 0.19);
        background-color: white;
    }

    .profile-img{
        height: 130px;
        width: 130px;
        border-radius: 50%;
        border : 3px solid chartreuse;
    }
</style>

<br><br><br>
<div class="container main-div">
    <div class="row">
        <div class="col-md-3 col-sm-12 me-4 sub-divs">
            <center style="margin: 20px;">
                <img src="https://www.bootdey.com/img/Content/avatar/avatar6.png" alt="" class="profile-img">
                <h5 style="margin-top: 15px;">{{profile.user.first_name}}</h5>
                <p style="margin-bottom: 0px;color: rgb(95, 92, 92);">{{profile.user.email}}</p>
                {% if profile.active %}
                <p style="color: rgb(105, 199, 10);">Online</p>
                {% else %}
                <p style="color: rgb(95, 92, 92);">Last Seen : {{profile.last_login}}</p>
                {% endif %}
                {% if profile.user in user.user_profile.follow.all %}
                <button class="btn btn-sm btn-warning" id="follow-btn"  onclick="followUser('unfollow');">Unfriend</button>
                <a type="button" href="{% url 'app:chatroom' %}?user={{profile.unique_id}}" class="btn btn-sm btn-outline-primary">Message</a >
                {% else %}
                {% ifnotequal profile.user user %}
                <button class="btn btn-sm btn-primary" id="follow-btn" onclick="followUser('follow');">Add Friend</button>
                <a type="button" href="{% url 'app:chatroom' %}?user={{profile.unique_id}}" class="btn btn-sm btn-outline-primary">Message</a >
                {% endifnotequal %}
                {% endif %}
               
                <hr>
            </center>

            <div style="margin: 20px;color: rgb(73, 72, 72);">
                <div class="row">
                    <div class="col-4"><h4><i class="fab fa-twitter" style="color: rgb(9, 169, 204);"></i></h4></div>
                    <div class="col-8"><p>@snape123</p></div>
                </div>

                <div class="row">
                    <div class="col-4"><h4><i class="fab fa-facebook-f me-2" style="color: rgb(6, 135, 163);"></i> </h4></div>
                    <div class="col-8"><p>@snape123</p></div>
                </div>

                <div class="row">
                    <div class="col-4"><h4><i class="fab fa-instagram me-2" style="color: rgb(204, 0, 170);"></i></h4></div>
                    <div class="col-8"><p>@snape123</p></div>
                </div>
                
            </div>
            
            
        </div>

        <div class="col-md-6 col-sm-12 ms-4 sub-divs p-4">
            <h5>Profile</h5>
            <hr>
            <form method="post" id="profileform">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-3 col-sm-12 me-2 mb-3"><p>Full Name : </p></div>
                    <div class="col-md-8 col-sm-12"> <input type="text" class="form-control profile-input" name="user_name" id="user_name" value="{{profile.user.first_name}}"></div>
                </div>
                <div class="row">
                    <div class="col-md-3 col-sm-12 me-2 mb-3"><p>Email : </p></div>
                    <div class="col-md-8 col-sm-12"> <input type="text" class="form-control profile-input" name="user_email" id="user_email" value="{{profile.user.email}}"></div>
                </div>
                <div class="row">
                    <div class="col-md-3 col-sm-12 me-2 mb-3"><p>Mobile : </p></div>
                    <div class="col-md-8 col-sm-12"> <input type="text" class="form-control profile-input" name="user_mobile" id="user_mobile" value="{{profile.mobile}}"></div>
                </div>
                <div class="row">
                    <div class="col-md-3 col-sm-12 me-2 mb-3"><p>Address : </p></div>
                    <div class="col-md-8 col-sm-12"> <input type="text" class="form-control profile-input" name="user_address" id="user_address" value="{{profile.address}}"></div>
                </div>
                <div class="row">
                    <div class="col-md-3 col-sm-12 me-2 mb-3"><p>Bio : </p></div>
                    <div class="col-md-8 col-sm-12"> <textarea name="user_bio" id="user_bio" cols="30" rows="3" class="form-control profile-input">{{profile.bio}}</textarea></div>
                </div>
                <div class="row mt-4">
                    <div class="col-md-3 col-sm-12 me-2 mb-3"></div>
                    <div class="col-md-8 col-sm-12"> <button type="button" class="btn btn-success" id="save-btn" onclick="update();">Save</button></textarea></div>
                </div>

            </form>
            
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script>
    {% ifnotequal profile.user user %}
    $("#profileform :input").prop("disabled", true);
    document.getElementById("save-btn").style.display = "none";
    {% endifnotequal %}
    function followUser(action){
        fetch("{% url 'user:followUser' %}?id={{profile.unique_id}}"+"&action="+action).then(res => res.json())
            .then(data => {
                if (data.result){
                    alert("Success");
                }
                else{
                    alert("Please try again")
                }
            });
    }
    const csrf = document.getElementsByName("csrfmiddlewaretoken")[0].value
    function update(){
        const data = {
            'user_name': document.getElementById("user_name").value,
            'user_email': document.getElementById("user_email").value,
            'user_mobile': document.getElementById("user_mobile").value,
            'user_bio': document.getElementById("user_bio").value,
            'user_address': document.getElementById("user_address").value
        }
        fetch('/auth/profileapi/{{profile.unique_id}}'+'/', {
        method: 'POST',
        body: JSON.stringify(data),
        headers: {
            'Content-type': 'application/json; charset=UTF-8',
            'X-CSRFToken': csrf
        }
        })
        .then(response => response.json())
        .then(data => {
            console.log(data)
            if (data.status == "success"){
                alert("Profile updated")
            }
            else{
                alert("Profile updation failed")
            }
        });

    }
</script>

{% endblock content %}

user/templates/user/register.html
{% extends "app/base.html" %}
{% block content %}

<style>
    body {
  background: #007bff;
  background: linear-gradient(to right, #0062E6, #33AEFF);
}

.card-img-left {
  width: 45%;
  /* Link to your background image using in the property below! */
  background: scroll center url('https://source.unsplash.com/WEQbe2jBg40/414x512');
  background-size: cover;
}

.btn-login {
  font-size: 0.9rem;
  letter-spacing: 0.05rem;
  padding: 0.75rem 1rem;
}

.btn-google {
  color: white !important;
  background-color: #ea4335;
}

.btn-facebook {
  color: white !important;
  background-color: #3b5998;
}

</style>

<br>
<div class="container">
    <div class="row">
      <div class="col-lg-10 col-xl-9 mx-auto">
        <div class="card flex-row my-5 border-0 shadow rounded-3 overflow-hidden">
          <div class="card-img-left d-none d-md-flex">
            <!-- Background image for card set in CSS! -->
          </div>
          <div class="card-body p-4 p-sm-5">
            <h5 class="card-title text-center mb-5 fw-light fs-5">Register</h5>
            <form>

              <div class="form-floating mb-3">
                <input type="email" class="form-control" id="email" placeholder="name@example.com">
                <label for="email">Email address</label>
              </div>

              <hr>

              <div class="form-floating mb-3">
                <input type="password" id="password1" class="form-control" id="floatingPassword" placeholder="Password">
                <label for="password1">Password</label>
              </div>

              <div class="form-floating mb-3">
                <input type="password" id="password2" class="form-control" id="floatingPasswordConfirm" placeholder="Confirm Password">
                <label for="password2">Confirm Password</label>
              </div>

              <div class="d-grid mb-2">
                <button class="btn btn-lg btn-primary btn-login fw-bold text-uppercase" type="button" onclick="register();">Register</button>
              </div>

              <a class="d-block text-center mt-2 small" href="{% url 'user:loginView' %}">Have an account? Sign In</a>

              <hr class="my-4">

              <!-- <div class="d-grid mb-2">
                <button class="btn btn-lg btn-google btn-login fw-bold text-uppercase" type="submit">
                  <i class="fab fa-google me-2"></i> Sign up with Google
                </button>
              </div>

              <div class="d-grid">
                <button class="btn btn-lg btn-facebook btn-login fw-bold text-uppercase" type="submit">
                  <i class="fab fa-facebook-f me-2"></i> Sign up with Facebook
                </button>
              </div> -->

            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

<script>
        const csrf = '{{csrf_token}}';
        function register(){
            email = document.getElementById("email").value;
            pass1 = document.getElementById("password1").value;
            pass2 = document.getElementById("password2").value;
            if (pass1 == pass2){
                const formData = new FormData();
                formData.append('email', email);
                formData.append('password1', pass1);
                formData.append('password2', pass2);
                const otherPram={
                    body:formData,
                    method:"POST",
                    headers: {
                        "X-CSRFToken": csrf
                    },
                    mode: "same-origin",
                };
                fetch("{% url 'user:register' %}", otherPram).then(res=>res.json())
                .then(data=>{
                    console.log(data);
                    if (data.status == "success"){
                  window.location = "{% url 'app:home' %}";
                }
                else{
                  alert(data.message)
                }
                });
            }
            else{
                alert("Password don't match");
            }
            
        }

        document.addEventListener("keyup", function(event) {
              if (event.keyCode === 13) {
                  event.preventDefault();
                  register();
              }
          });

</script>

{% endblock content %}