app/urls.py
from django.urls import path
from . import views

app_name = "app"

urlpatterns = [
    path('', views.home, name='home'),
    path('start/chat/', views.startRoom, name='startRoom'),
    path('chat/<str:room_id>', views.enterRoom, name='enterRoom'),
    path('manage/online/', views.manageOnlineUsers, name="manageOnlineUsers"),
    path('location/update/', views.locationSharing, name="locationSharing"),
    path('lobby/<str:room_id>', views.waitRoom, name="waitRoom"),
    path('chat/response/', views.roomResponse, name='roomResponse',),
    path("sendInvite/", views.sendInvite, name="sendInvite"),
    path('delete/room/<str:room_id>', views.deleteRoom, name="deleteRoom"),
    path("chatroom", views.chatroom, name="chatroom")
]

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('logout/', views.user_logout, name="logout"),
    path('register/', views.registerView, name='registerView'),
    path('api/register/', views.register, name='register'),
    path('login/', views.loginView, name="loginView"),
    path("api/login/", views.user_login, name="login"),
    path('profile/<str:id>/', views.profile, name="profile"),
    path('search/', views.autocomplete, name='autocomplete'),
    path('follow/', views.follow_user, name='followUser'),
    path('profileapi/<str:id>/', views.profileAPI, name="profileAPI")
]

videochat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('auth/', include('user.urls')),
]

app/templates/app/121.html
{% extends "app/base.html" %}
{% block content %}
    <style>
      .switch {
  position: relative;
  display: inline-block;
  width: 40px;
  height: 24px;
      }

.switch input { 
  opacity: 0;
  width: 0;
  height: 0;
}

.slider {
  position: absolute;
  cursor: pointer;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: #ccc;
  -webkit-transition: .4s;
  transition: .4s;
}

.slider:before {
  position: absolute;
  content: "";
  height: 16px;
  width: 16px;
  left: 4px;
  bottom: 4px;
  background-color: white;
  -webkit-transition: .4s;
  transition: .4s;
}

input:checked + .slider {
  background-color: #2196F3;
}

input:focus + .slider {
  box-shadow: 0 0 1px #2196F3;
}

input:checked + .slider:before {
  -webkit-transform: translateX(26px);
  -ms-transform: translateX(26px);
  transform: translateX(16px);
}

/* Rounded sliders */
.slider.round {
  border-radius: 24px;
}

.slider.round:before {
  border-radius: 50%;
}

video{
    border-radius: 8px;
    border:1px solid #929494;
}

.spl-col-1{
  border: 3px solid #827e7e ;
}

.spl-col-2{
  border:3px solid #827e7e;
}
    </style>
    <div style="padding: 10px;border-radius: 5px; color:white;" >
      <div class="row ms-5">

        <div class="col-md-9 me-5 spl-col-1" style="background-color: #303030; margin-left:4px;border-radius: 8px;padding-top: 15px;padding-bottom: 15px;">
            <div class="row">
                <div class="col-md-4 video">
                    <video id="local-video" muted autoplay width="300" height="200"></video>
                </div>
          
                <div class="col-md-4 video">
                  <video id="remote-video" autoplay width="300" height="200"></video>
                </div>
                
                <div class="col-md-4 video">
                  <video id="remote-video" autoplay width="300" height="200"></video>
                </div>
            </div>

            <div class="row">
              <div class="col-md-4 video">
                  <video id="local-video" muted autoplay width="300" height="200"></video>
              </div>
        
              <div class="col-md-4 video">
                <video id="remote-video" autoplay width="300" height="200"></video>
              </div>
              
              <div class="col-md-4 video">
                <video id="remote-video" autoplay width="300" height="200"></video>
              </div>
          </div>

          <div class="row">
            <div class="col-md-4 video">
                <video id="local-video" muted autoplay width="300" height="200"></video>
            </div>
      
            <div class="col-md-4 video">
              <video id="remote-video" autoplay width="300" height="200"></video>
            </div>
            
            <div class="col-md-4 video">
              <video id="remote-video" autoplay width="300" height="200"></video>
            </div>
        </div>
        </div>

        <div class="col-md-2 spl-col-2" style="background-color: #303030;border-radius: 8px;">
         
            <div class="" id="call-dialog">
              <label for="call_to">Make call to : </label>
              <form class="d-flex">
                <input class="form-control me-2" id="call_to" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-success" onclick="call();" type="button">Call</button>
              </form>
            </div>

            <div id="receive-dialog" style="display: none;">
              <h4 id="call-receive-msg"></h4>
              <button class="btn btn-success" id="answer" onclick="answer();">Answer</button>
            </div>
      
            <hr>
            <h5><b></b>Online Users</b></h5>
              <ul id="online-list">
                {% for i in online_users %}
                    <li><a href="">{{i}}</a></li>
                {% endfor %}
              </ul>
        </div>
      </div>
      
      </div>
          

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<script>
  let myName = '{{username}}';
  let chatSocket;
  let localVideo = document.getElementById("local-video");
  let remoteVideo = document.getElementById("remote-video");
  let callDialog = document.getElementById("call-dialog");
  let receiveDialog = document.getElementById("receive-dialog");
  let onlineList = document.getElementById("online-list");
  let activeBtn = document.getElementById("active-btn");
  let myPosition = document.getElementById("position");
  let localVideoStream;
  let call_to;
  let peerConnection;
  let remoteOffer;

  document.getElementById("activeDiv").style.display = "block";
  activeBtn.style.display = "block";
  activeBtn.checked = false;
  myPosition.style.display = "block";

  document.getElementById("location").style.display = "block";

  let ICEconfig = {
    iceServers: [
        {   urls: [ "stun:bn-turn1.xirsys.com" ]}, 
        {   username: "WtJcHNTgNpN90FSvMVmZtWWVztiHEhbFfsdRyMS1f_PoMfbjWJSW_rVXiivC4VCOAAAAAGGZQvNhc2hpc2hzYXNtYWwx",   
        credential: "6e26a8e4-4a32-11ec-8f0c-0242ac140004",   
        urls: [       
            "turn:bn-turn1.xirsys.com:80?transport=udp",       
            "turn:bn-turn1.xirsys.com:3478?transport=udp",       
            "turn:bn-turn1.xirsys.com:80?transport=tcp",       
            "turn:bn-turn1.xirsys.com:3478?transport=tcp",       
            "turns:bn-turn1.xirsys.com:443?transport=tcp",       
            "turns:bn-turn1.xirsys.com:5349?transport=tcp"   
        ]}]
    }

  const mediaConstraints = {
    "video" : true,
    "audio" : true
  }

  let iceCandidatesList = []

  function play() {
	  var audio = new Audio('https://2u039f-a.akamaihd.net/downloads/ringtones/files/mp3/xperia-artic-54206.mp3');
	  audio.play();
	}

  function connectWebSocket(){
      var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
      chatSocket = new WebSocket(ws_scheme+'://' +window.location.host +'/ws/chat/');
      console.log("Websocket connected");

      chatSocket.onopen = event =>{
          chatSocket.send(JSON.stringify({
                "type": "login",
                "to": myName,
                "message" : "Web socket working"
            }));
      }

      chatSocket.onmessage = (e) =>{
        const data = JSON.parse(e.data);
        console.log(data);

        let type = data.type;
        if (type == "answer"){
            console.log("Call answered")
            peerConnection.setRemoteDescription(data.answer);
        }

        else if (type == "candidate"){
            console.log("ICE candidate received")
            handleIncomingICEcandidate(data);
        }

        else if (type == "offer"){
            console.log("Receiving call from "+call_to);
            handleIncomingcall(data);
        }

        else if (type == "online_traffic"){
            let action = data.action;
            if (action == "remove"){
                var elem = document.getElementById(data.user);
                elem.parentNode.removeChild(elem);
            }
            else{
                onlineList.innerHTML += `<li id='${data.user}'>${data.user}</li>`
            }
        }
      }

      chatSocket.onclose = (e) =>{
        alert("Socket disconnected");
      }
  }

  function sendSocket(data){
      if (chatSocket){
          data.to = call_to;
          data.from = myName;
          console.log(data);
          chatSocket.send(JSON.stringify(
            data
          ));
      }
      else{
          console.log("Chat socket not connected")
      }
  }

  function handleIncomingICEcandidate(data){
    if (peerConnection){
        peerConnection.addIceCandidate(data.candidate);
    }
    else{
        console.log("RTC peer connection not set");
        iceCandidatesList.push(data.candidate);
    }
  }

  function handleIncomingcall(data){
      call_to = data.from;
      receiveDialog.style.display = "block";
      callDialog.style.display = "none";
      remoteOffer = data.offer;
      play();
  }

  function manageSocket(){
      if (activeBtn.checked){
          connectWebSocket();
      }
      else{
          if (chatSocket){
              chatSocket.close();
              console.log("Socket closed")
          }
          else{
              console.log("Socket not connected");
          }
      }
  }

  function createAndSendAnswer(){
    peerConnection.setRemoteDescription(remoteOffer);
    peerConnection.createAnswer((answer) => {
      peerConnection.setLocalDescription(answer);
        if ( iceCandidatesList.length >0 ){
          for (let i=0; i<iceCandidatesList.length; i++){
              try {
                  peerConnection.addIceCandidate(iceCandidatesList[i]);
              }
              catch (error) {
                  console.log(error);
              }
          }
          iceCandidatesList = [];
        }
        else{
            console.log("No ICE candidates found!");
        }
        sendSocket({
            type: "answer",
            answer: answer
        })
      }, error => {
            console.log(error);
          })
        }

  function answer(){
    accessMedia().then(bool => {
          createAndSendAnswer()
      })
  }

  function call(){
    call_to = document.getElementById("call_to").value;
    accessMedia().then(
      bool => {
          createAndSendOffer()
      })
  }

  function createAndSendOffer(){
      peerConnection.createOffer((offer) => {
          sendSocket({
              type: "offer",
              offer: offer
          })
      peerConnection.setLocalDescription(offer)
      }, (error) => {
        console.log(error)
      })
  }

  function accessMedia(){
    return navigator.mediaDevices.getUserMedia(mediaConstraints)
      .then(stream => {
          localVideoStream = stream;
          localVideo.srcObject = localVideoStream;
          return createRTCPeerConnection();
          
      }).catch(function (error) {
        console.log(error)
      });
  }

  function createRTCPeerConnection(){
      peerConnection = new RTCPeerConnection(ICEconfig);
      // peerConnection = new RTCPeerConnection(null);
      peerConnection.onaddstream = handleAddStream;
      peerConnection.onicecandidate = handleICEcandidate;
      peerConnection.addStream(localVideoStream);
      return;
  }
  
  function handleAddStream(event){
      remoteStream = event.stream;
      remoteVideo.srcObject = remoteStream;
  }

  function handleICEcandidate(event){
    if (event.candidate == null)
        return;
    sendSocket({
        type: "candidate",
        candidate: event.candidate
    })
  }
  
</script>

{% endblock content %}

app/templates/app/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cabin&family=Gochi+Hand&display=swap" rel="stylesheet">
    <title>Hey! There</title>
    <style>

      .navbar
        {
            border-radius: 8px;
            font-family: 'Cabin', sans-serif;
        }
    </style>
  </head>
  <body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow fixed-top ms-2 me-2 mt-2">
      <div class="container">
        <a class="navbar-brand" href="{% url 'app:home' %}"><h3><b>Hey! There</b></h3></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ms-auto">
            {% if user.is_authenticated %}
            <li class="nav-item dropdown me-2">
              <a type="button" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><h2><i class="fas fa-user-circle"></i></h2></a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url 'user:profile' user.user_profile.unique_id %}"><b>Profile</b></a></li>
                <li><a class="dropdown-item" href="{% url 'user:logout' %}"><b>Logout</b></a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">{{user}}</a></li>
              </ul>
            </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'app:startRoom' %}"><h5><b>Host Meet</b></h5></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" type="button" data-bs-toggle="modal" data-bs-target="#exampleModal"><h5><b>Join Meet</b></h5></a>
              </li>
            {% else %}
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'user:loginView' %}"><h5><b>Login</b></h5></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'user:registerView' %}"><h5><b>Register</b></h5></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.linkedin.com/in/ashish-sasmal/"><h5><b>About</b></h5></a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

      <br><br>
      
    {% block content %}

    {% endblock content %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script>
      function copyId(val){
        navigator.clipboard.writeText(val);
      }

      function getLocation() {
          if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(showPosition);
          } else {
            myPosition.innerHTML = "Geolocation is not supported by this browser.";
          }
      }

      function showPosition(position) {
      
          myPosition.style.display = "block";
          myPosition.innerHTML = "<i class='fas fa-map-marker-alt'></i> " + position.coords.latitude +
          ", " + position.coords.longitude;
          fetch(`{% url 'app:locationSharing' %}?lat=${position.coords.latitude}&long=${position.coords.longitude}&action=add&username=`+'{{user.user_profile.unique_id}}').then(res=>res.json()).then(data=>{
              console.log(data);
          });
      }

      {% if user.is_authenticated %}
      let myDetails = {"id": '{{request.user.user_profile.unique_id}}', "name": '{{request.user.username}}'};
      function connectWebSocket(){
            var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
            chatSocket = new WebSocket(ws_scheme+'://' +window.location.host +'/ws/user/{{request.user.user_profile.unique_id}}/');
            console.log("Websocket connected");

            chatSocket.onmessage = async(e) =>{
                const data = JSON.parse(e.data);
                console.log(data);
                if (data.type == "room_request"){
                    if (data.response == "accept"){
                        alert("Accepted")
                        window.location = "/chat/"+data.room_id
                    }
                    else{
                        alert("Request denied.");
                        window.location = "/"
                    }
                }
            }

            chatSocket.onopen = event =>{
                chatSocket.send(JSON.stringify({
                      "type": "login",
                      "from": myDetails
                  }));
            }
        }
      var loc = window.location.href.split("?")[0].split("/");
      if (loc[loc.length-1] != "chatroom"){
        connectWebSocket()
      }
        
      {% endif %}
    </script>
  </body>
</html>

app/templates/app/home.html
{% extends "app/base.html" %}
{% block content %}

<style>
  body{
      background-image: url("https://images.unsplash.com/photo-1585974738771-84483dd9f89f");
      background-size: 100% 150%;
      
  }

  .green-dot {
    height: 10px;
    width: 10px;
    background-color: greenyellow;
    border-radius: 50%;
    display: inline-block;
  }

  .red-dot {
    height: 10px;
    width: 10px;
    background-color: red;
    border-radius: 50%;
    display: inline-block;
  }

  .ui-autocomplete{
    background-color: white;
    overflow-y:scroll;
  }
  
  .ui-helper-hidden-accessible{
    display: none;
  }

  #ui-id-1{
      width: 200px !important;
  }
</style>

<br><br><br>
<div class="position-fixed top-0 end-0 p-3" style="z-index: 5">
	<div id="primary_toast" class="toast hide text-white bg-primary border-0" role="alert" aria-live="assertive" aria-atomic="true">
	<div class="toast-body" id="primary_toast_msg">
	</div>
	</div>
	</div>

	<div class="position-fixed top-0 end-0 p-3" style="z-index: 5">
	<div id="success_toast" class="toast hide text-white bg-success border-0" role="alert" aria-live="assertive" aria-atomic="true">
	<div class="toast-body" id="success_toast_msg">
	</div>
	</div>
	</div>

	<div class="position-fixed top-0 end-0 p-3" style="z-index: 5">
	<div id="danger_toast" class="toast hide text-white bg-danger border-0" role="alert" aria-live="assertive" aria-atomic="true">
	<div class="toast-body" id="danger_toast_msg">
	</div>
	</div>
	</div>

	<div class="position-fixed top-0 end-0 p-3" style="z-index: 5">
	<div id="warning_toast" class="toast hide text-white bg-warning border-0" role="alert" aria-live="assertive" aria-atomic="true">
	<div class="toast-body" id="warning_toast_msg">
	</div>
	</div>
	</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Join Meet</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form action="" method="POST">
        {% csrf_token %}
      <div class="modal-body">
        
            <label for="room_id">Enter Room Code</label>
            <input type="text" class="form-control" name="room_id" id="room_id">
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Enter</button>
      </div>
    </form>
    </div>
  </div>
</div>

{% if user.is_authenticated %}
<div class="container">
  <h1 style="color: white;font-family: 'Gochi Hand', cursive;" class="ms-5"><b>Dashboard</b> <hr></h1>
  <div class="row" style="min-height: 300px;max-height: 300px;">
    <div class="col-sm-10 col-md-5 col-lg-5 p-3 mb-4 rounded-3 me-3 table-responsive" style="background-color: #232b2b;max-height: 300px;color: white;float: none; margin: 0 auto;">
      <caption><h4>Recents Calls</h4></caption>
      <table class="table" style="color: white;">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Room</th>
            <th scope="col">Last Seen</th>
          </tr>
        </thead>
        <tbody>
          {% for room in rooms %}
              <tr id="r-{{room.room_id}}">
                <th scope="row">#</th>
                <td><a href="{% url 'app:enterRoom' room.room_id %}" style="text-decoration: none;">{{room.room_id}}</a></td>
                <td>{{room.last_active | date:'d-m-Y H:i'}}</td>
                <td><a type="button" onclick="deleteRoom('{{room.room_id}}')"><i class="fas fa-trash" style="color: red;"></i></a></td>
              </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  
    <div class="col-sm-10 col-md-5 col-lg-5 p-3 mb-4 bg-light rounded-3 table-responsive" style="max-height: 300px;float: none; margin: 0 auto;">
      <caption><h4>My Friends</h4></caption>
      <table class="table table-hover">   
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Status</th>
            <th scope="col">Handle</th>
          </tr>
        </thead>
        <tbody>
          {% for user in request.user.user_profile.follow.all %}
              <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td><a href="{% url 'user:profile' user.user_profile.unique_id %}" style="text-decoration: none;">{% if user.first_name %}{{user.first_name}}{% else %}{{user.username}}{% endif %}</a></td>
                <td>{% if user.user_profile.active %}<p style="color: #21a617;"><span class="green-dot"></span> Online</p>{% else %}<p style="color: crimson;"><span class="red-dot"></span> Offline</p>{% endif %}</td>
                <td><a href="{% url 'app:chatroom' %}?user={{user.user_profile.unique_id}}"><h4><i class="fas fa-comment-alt"></i></h4></a></td>
              </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    
    
  </div>
  <br>
  <div class="row">
    <div class="col-sm-6 col-md-6 center-block" style="margin-left: auto;margin-right: auto;">
      <form class="d-flex form-control">
        <input type="hidden" name="mysearchid" value="" id="mysearchid">
        <input class="form-control ui-widget me-2" type="search" name="mysearch" id="inputid" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="button" onclick="searchUser();">Search</button>
      </form>
    </div>
    
  </div>

</div>
{% else %}
<div class="container col-8">
  <div class="p-4 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5" style="background-color: #e8e8e8;">
      <h3 class="fw-bold">Hey! Friend :) {{user.username}}</h3>
      <p class="col-md-8 fs-3">“Live your life, listen to your music way too loud, be crazy and as different as you want to be and always remember you're not alone.”</p>
      <p class="fs-12"><i>- Andy Biersack</i></p>
      <a type="button" class="btn btn-primary" href="{% url 'app:startRoom' %}" type="button">Let's Start</a>
    </div>
  </div>
</div>
{% endif %}

<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script>
  $("#inputid").autocomplete({
    source:"{% url 'user:autocomplete' %}",
    focus: function( event, ui ) {
          $( "#inputid" ).val( ui.item.label );
             return false;
       },
       select: function( event, ui ) {
          $( "#inputid" ).val( ui.item.label );
          $( "#mysearchid" ).val( ui.item.value );
          return false;
       }
    });

    function searchUser(){
        id = document.getElementById("mysearchid").value;
        window.location = "/auth/profile/"+id;
    }

    function deleteRoom(room_id){
      fetch("/delete/room/"+room_id).then(res => res.json())
      .then(data => {
          if (data.result){
              alert("Room deleted successfully!");
              var elem = document.getElementById('r-'+room_id);
              if (elem) {
                  elem.parentNode.removeChild(elem);
              }
          }
          else{
              alert("Failed to delete room");
          }
      });
    }
</script>

{% endblock content %}

app/templates/app/waitroom.html
{% extends "app/base.html" %}
{% block content %}

<title>Waiting Lobby</title>
    <style>
        .loader {
          border: 16px solid #f3f3f3;
          border-radius: 50%;
          border-top: 16px solid #82807a;
          border-bottom: 16px solid #82807a;
          width: 120px;
          height: 120px;
          -webkit-animation: spin 2s linear infinite;
          animation: spin 2s linear infinite;
        }
        
        @-webkit-keyframes spin {
          0% { -webkit-transform: rotate(0deg); }
          100% { -webkit-transform: rotate(360deg); }
        }
        
        @keyframes spin {
          0% { transform: rotate(0deg); }
          100% { transform: rotate(360deg); }
        }
    </style>


    <div class="container" align="center" style="margin-top: 10%;">
        <div class="loader"></div>
        <br>
        <h4><b>Wait while someone allow you...</b></h4>
    </div>

{% endblock content %}